# Serveur
server.port=8080

# Base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fsm_navigator
spring.datasource.username=postgres
spring.datasource.password=momenh2004

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=fsm_navigator_secret_key_2024_monastir
jwt.expiration=86400000

admin.email=hellaramomen8@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hellaramomen8@gmail.com
spring.mail.password=dcyk czrd jyft kmrk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true